#!/bin/bash
#Mihhail Matisinets
#IS216
#

#Skripti algus
#väljastame menü
read -p "Press Enter to see our menu."
echo "=========MENU========="
cat -b menu1 menu2 menu3

read -p "Please, enter a given number(1, 2, 3): "  ch

if [ $ch -eq 1 ];then
	echo  "Stick to your ribs."
	echo  "Watch your cholesterol."
	echo  "Enjoy your meal!"
elif [ $ch -eq 2 ];then
	echo  "British are coming!"
	echo  "Enjoy your meal!"
elif [ $ch -eq 3 ];then
	echo  "Health foods..."
	echo  "Dieting is os boring."
	echo  "Enjoy your meal!"
#kui number ei ole valitud
else [ -z "$ch" ];
	echo "Please, enter the number."
fi 

